// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// ---------------------------------------------------------------------------
/// ResUniq - firebase_options.dart
/// ---------------------------------------------------------------------------
/// PURPOSE:
/// Generated Firebase configuration selected automatically for the current platform. Normally this file is maintained by FlutterFire CLI.
///
/// BEGINNER GUIDE:
/// - UI screens/widgets should mainly display information and collect input.
/// - Providers hold/change state that the UI listens to.
/// - Services/repositories perform Firebase, API, PDF, or other data work.
/// - Models describe the data passed between these layers.
///
/// TIP:
/// Read this file together with the classes it imports. The imported classes
/// usually explain where data comes from and where actions are performed.
/// ---------------------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNLHDUCG9zq_n89LUX76sIMfujp9N7mH4',
    appId: '1:1070058196039:web:a36aec37ebf06326c1b562',
    messagingSenderId: '1070058196039',
    projectId: 'resuniq-ca89d',
    authDomain: 'resuniq-ca89d.firebaseapp.com',
    storageBucket: 'resuniq-ca89d.firebasestorage.app',
    measurementId: 'G-KXFQJ8DGX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQcXft47MUHwolDw2V7hHxaNZ3tYV8Ka4',
    appId: '1:1070058196039:android:2f32694f30c377cac1b562',
    messagingSenderId: '1070058196039',
    projectId: 'resuniq-ca89d',
    storageBucket: 'resuniq-ca89d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjp2QnndhUNXGeaErLesVxZNgLAP9gPzE',
    appId: '1:1070058196039:ios:44ffd5653b5fa533c1b562',
    messagingSenderId: '1070058196039',
    projectId: 'resuniq-ca89d',
    storageBucket: 'resuniq-ca89d.firebasestorage.app',
    iosBundleId: 'com.example.resumeClaudeWithBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjp2QnndhUNXGeaErLesVxZNgLAP9gPzE',
    appId: '1:1070058196039:ios:44ffd5653b5fa533c1b562',
    messagingSenderId: '1070058196039',
    projectId: 'resuniq-ca89d',
    storageBucket: 'resuniq-ca89d.firebasestorage.app',
    iosBundleId: 'com.example.resumeClaudeWithBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNLHDUCG9zq_n89LUX76sIMfujp9N7mH4',
    appId: '1:1070058196039:web:aa9ea5344898abf8c1b562',
    messagingSenderId: '1070058196039',
    projectId: 'resuniq-ca89d',
    authDomain: 'resuniq-ca89d.firebaseapp.com',
    storageBucket: 'resuniq-ca89d.firebasestorage.app',
    measurementId: 'G-P9YJC3QSLD',
  );
}
